/** 마이페이지·목록 카드에 필요한 matchups 컬럼 (select * 대신) */
export const MY_PAGE_MATCHUP_CARD_COLUMNS = [
  'id',
  'user_id',
  'created_at',
  'status',
  'expires_at',
  'title',
  'total_votes',
  'left_votes',
  'right_votes',
  'right_type',
  'right_user_id',
  'left_thumbnail_url',
  'right_thumbnail_url',
  'left_type',
  'right_type',
  'left_url',
  'right_url',
  'left_text',
  'right_text',
  'left_label',
  'right_label',
].join(', ')

/** 매치업 상세 본문 (미디어·투표·메타). 작성자는 embed profiles */
export const MATCHUP_DETAIL_MATCHUP_COLUMNS = [
  'id',
  'user_id',
  'right_user_id',
  'title',
  'description',
  'right_title',
  'right_description',
  'category',
  'tags',
  'created_at',
  'expires_at',
  'status',
  'left_label',
  'right_label',
  'left_type',
  'right_type',
  'left_url',
  'right_url',
  'left_text',
  'right_text',
  'left_thumbnail_url',
  'right_thumbnail_url',
  'left_votes',
  'right_votes',
  'total_votes',
  'comments_count',
  'likes_count',
  'challenger_forfeit_at',
  'feed_banner_highlight_until',
  'is_demo',
].join(', ')
