-- =============================================================================
-- (통합됨) 카카오/구글용 별도 handle_new_user 는 유지보수 혼선을 일으켜
-- supabase_handle_new_user_unified.sql 한 곳으로 합쳤습니다.
--
--   → supabase_handle_new_user_unified.sql
--
-- unified 트리거는 nickname 우선 + name/full_name 등 소셜 필드 + avatar_url/picture 를 반영합니다.
-- =============================================================================
