-- =============================================
-- [사용 중단] appeals 가상 데이터 시드
--
-- 더미 삭제: supabase_delete_seed_appeals.sql (SQL Editor 1회 실행)
-- 관리자 앱: src/lib/appealAdminStorage.js — VS-2025/2026 시드·user_* 가상 id 자동 제외
-- =============================================
